"""create users table

Revision ID: f0e6bdcc7acb
Revises: c0c3bb53323f
Create Date: 2026-07-10 11:54:01.787071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e6bdcc7acb'
down_revision: Union[str, Sequence[str], None] = 'c0c3bb53323f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('documents', sa.Column('course', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('subject', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=False))
    document_type = sa.Enum('BOOK', 'CHAPTER', 'NOTES', 'QUESTION_BANK', 'MCQ', 'TRANSCRIPT', 'GLOSSARY', 'FORMULA_SHEET', 'CHEAT_SHEET', 'OTHER', name='documenttype')
    document_type.create(op.get_bind())
    op.add_column('documents', sa.Column('document_type', document_type, nullable=True))
    op.add_column('documents', sa.Column('upload_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'documents', 'users', ['upload_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'upload_by')
    op.drop_column('documents', 'document_type')
    document_type = sa.Enum('BOOK', 'CHAPTER', 'NOTES', 'QUESTION_BANK', 'MCQ', 'TRANSCRIPT', 'GLOSSARY', 'FORMULA_SHEET', 'CHEAT_SHEET', 'OTHER', name='documenttype')
    document_type.drop(op.get_bind())
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'subject')
    op.drop_column('documents', 'course')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
